version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: hello_world
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
